trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  # My azure web app name:
  webAppName: 'app-release-gate-mopo'
  sonarOrganization: 'mopodevops'
  sonarProjectKey: 'MoPoOps_azure-devsecops-release-gate'

stages:
- stage: BuildStage
  displayName: 'Build, Scan, and Package'
  jobs:
  - job: BuildJob
    steps:
    # Prepare SAST scanning
    - task: SonarCloudPrepare@2
      displayName: 'Prepare SonarCloud analysis'
      inputs:
        SonarCloud: 'sc-sonar-connection'
        organization: '$(sonarOrganization)'
        scannerMode: 'MSBuild'
        projectKey: '$(sonarProjectKey)'
        projectName: 'azure-devsecops-release-gate'

    - task: DotNetCoreCLI@2
      displayName: 'Restore dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build the application'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    # Static source Code security scan
    - task: SonarCloudAnalyze@2
      displayName: 'Run SonarCloud Code Analysis'

    # Stop the pipeline if the quality gate fails
    - task: SonarCloudPublish@2
      displayName: 'Publish Quality Gate Result'
      inputs:
        pollingTimeoutSec: '300'

    - task: DotNetCoreCLI@2
      displayName: 'Publish and Zip'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: 'Save the Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'release-gate-drop'
        publishLocation: 'Container'

- stage: DeployStage
  displayName: 'Deploy to Azure'
  dependsOn: BuildStage
  condition: succeeded()
  jobs:
  - job: DeployJob
    steps:
    - DownloadBuildArtifacts@0
      displayName: 'Download the Artifact'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'release-gate-drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: AzureWebApp@1
      displayName: 'Azure Web App Deploy'
      inputs:
        azureSubscription: 'sc-azure-connection'
        appType: 'webAppLinux'
        appName: '$(webAppName)'
        package: '$(System.ArtifactsDirectory)/release-gate-drop/*.zip'